services:
  news-ms:
    build: news-laptops-ms
    container_name: news-ms
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - 'lappy_network'
  
  specs_micro:
    build: specs-micro/
    container_name: lappy_specs
    ports:
      - '8001:8001'
    networks:
      - 'lappy_network'
    depends_on:
      - mongodb

  rating_app:
    networks:
      - 'lappy_network'
    build: LaptopRater/
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    networks:
      - 'lappy_network'
  
  mongorestore:
    image: mongodb/mongodb-community-server
    command: ["mongorestore --host mongodb --port 27017 --db laptops --collection specs /specs.bson"]
    volumes:
      - ./data/mongorestore/specs.bson:/specs.bson
    depends_on:
      - mongodb
    networks:
      - 'lappy_network'
    entrypoint: ["/bin/sh", "-c"]
    restart: "no"

  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: [ "run", "-c", "krakend.json" ]
    depends_on:
      - news-ms
    networks:
      - 'lappy_network'

networks:
  lappy_network:
    driver: bridge
